modules/MubAdmin/modules/item/models/Product.php
<?php

namespace app\modules\MubAdmin\modules\item\models;
use app\models\MubUser;
use Yii;

/**
 * This is the model class for table "item".
 *
 * @property int $id
 * @property int $mub_user_id
 * @property string $model_number
 * @property string $item_package_quantity
 * @property string $size
 * @property string $size_map
 * @property string $color
 * @property string $color_map
 * @property string $enclosure_material
 * @property int $manufacturer
 * @property string $title
 * @property int $manufacturer_part_number
 * @property int $brand
 * @property string $category
 * @property string $sub_category
 * @property string $seller_sku
 * @property string $HSN_code
 * @property int $price
 * @property int $sale_price
 * @property string $warranty_des
 * @property string $country
 * @property string $release_date
 * @property string $sale_start_date
 * @property string $sale_end_date
 * @property string $restock_date
 * @property string $offer_release_date
 * @property string $condition_notes
 * @property string $leagle_notes
 * @property int $quantity
 * @property int $max_order_quantity
 * @property string $product_text_code
 * @property string $condition
 * @property string $handling_time
 * @property string $gift_wrap
 * @property string $status
 * @property string $created_at
 * @property string $updated_at
 * @property string $del_status 0-Active,1-Deleted DEFAULT 0
 *
 * @property MubUser $mubUser
 * @property ItemImages[] $itemImages
 */
class Product extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'item';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['mub_user_id', 'manufacturer', 'manufacturer_part_number', 'brand', 'price', 'sale_price', 'quantity', 'max_order_quantity'], 'integer'],
            [['item_package_quantity', 'gift_wrap', 'status', 'del_status'], 'string'],
            [['created_at', 'updated_at'], 'safe'],
            [['model_number', 'size', 'size_map', 'color', 'color_map', 'enclosure_material', 'title', 'category', 'sub_category', 'seller_sku', 'HSN_code', 'warranty_des', 'country', 'release_date', 'sale_start_date', 'sale_end_date', 'restock_date', 'offer_release_date', 'condition_notes', 'leagle_notes', 'product_text_code', 'condition', 'handling_time'], 'string', 'max' => 255],
            [['mub_user_id'], 'exist', 'skipOnError' => true, 'targetClass' => MubUser::className(), 'targetAttribute' => ['mub_user_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'mub_user_id' => 'Mub User ID',
            'model_number' => 'Model Number',
            'item_package_quantity' => 'Item Package Quantity',
            'size' => 'Size',
            'size_map' => 'Size Map',
            'color' => 'Color',
            'color_map' => 'Color Map',
            'enclosure_material' => 'Enclosure Material',
            'manufacturer' => 'Manufacturer',
            'title' => 'Title',
            'manufacturer_part_number' => 'Manufacturer Part Number',
            'brand' => 'Brand',
            'category' => 'Category',
            'sub_category' => 'Sub Category',
            'seller_sku' => 'Seller Sku',
            'HSN_code' => 'Hsn Code',
            'price' => 'Price',
            'sale_price' => 'Sale Price',
            'warranty_des' => 'Warranty Des',
            'country' => 'Country',
            'release_date' => 'Release Date',
            'sale_start_date' => 'Sale Start Date',
            'sale_end_date' => 'Sale End Date',
            'restock_date' => 'Restock Date',
            'offer_release_date' => 'Offer Release Date',
            'condition_notes' => 'Condition Notes',
            'leagle_notes' => 'Leagle Notes',
            'quantity' => 'Quantity',
            'max_order_quantity' => 'Max Order Quantity',
            'product_text_code' => 'Product Text Code',
            'condition' => 'Condition',
            'handling_time' => 'Handling Time',
            'gift_wrap' => 'Gift Wrap',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'del_status' => 'Del Status',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMubUser()
    {
        return $this->hasOne(MubUser::className(), ['id' => 'mub_user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getItemImages()
    {
        return $this->hasMany(ItemImages::className(), ['item_id' => 'id']);
    }
}

modules/MubAdmin/modules/item/controllers/ProductController.php
<?php

namespace app\modules\MubAdmin\modules\item\controllers;

use Yii;
use app\components\MubController;
use yii\web\UploadedFile;
use yii\helpers\BaseFileHelper;
use yii\helpers\FileHelper;
use yii\helpers\Json;
use app\modules\MubAdmin\modules\item\models\Product;
use app\modules\MubAdmin\modules\item\models\ProductSearch;
use app\modules\MubAdmin\modules\item\models\ProductProcess;
use app\modules\MubAdmin\modules\item\models\ProductImages;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * Default controller for the `Product` module
 */
class ProductController extends MubController
{
    public function getPrimaryModel()
   {
        return new Product();
   }

   public function getProcessModel()
   {
        return new ProductProcess();
   }

   public function getSearchModel()
   {
        return new ProductSearch();
   }

   public function actionProductImage($userId)
   {
    if (\Yii::$app->request->isAjax) {
      $model = new ProductImages();

      $imageFile = UploadedFile::getInstance($model, 'thumbnail_url');

      $directory = \Yii::getAlias('@app/images/product') . DIRECTORY_SEPARATOR.$userId;
      if (!is_dir($directory)) {
          FileHelper::createDirectory($directory);
      }

      if ($imageFile) {
          $uid = uniqid(time(), true);
          $fileName = $uid . '.' . $imageFile->extension;
          $filePath = $directory . $fileName;
          if ($imageFile->saveAs($filePath)) {
              $path = '/images/product/'. $userId.DIRECTORY_SEPARATOR.$fileName;
              $model->mub_user_id = $userId;
              $model->item_id = NULL;
              $model->full_path = $path;
              $model->thumbnail_url = $path;
              if(!$model->save())
              {
                p($model->getErrors());
              }
              
              $successPath = '/images/done.png';
              return Json::encode([
                  'files' => [
                      [
                          'name' => $fileName,
                          'size' => $imageFile->size,
                          'url' => $successPath,
                          'thumbnailUrl' => $successPath,
                          'deleteUrl' => 'image-delete?name=' . $fileName,
                          'deleteType' => 'POST',
                      ],
                  ],
              ]);
          }
      }
      return '';
    }else
    {
      return 'go away';
    }
  }

  public function actionImageDelete($name)
  {
     if (\Yii::$app->request->isAjax) {
      $stateId = \Yii::$app->request->getQueryParam('state');
      $directory = \Yii::getAlias('@app/images/product') . DIRECTORY_SEPARATOR;
      if (is_file($directory.$name)) 
      {
          if(unlink($directory . $name))
          {
            $productImages = new \app\modules\MubAdmin\modules\item\models\ProductImages();
            $success = $productImages::deleteAll(['title' => $name]);
            if($success)
            {
              return 'Image Deleted Successfully'; 
            }
          }else
          {
            return 'There was a problem deleting the Image';
          }
      }
      else
      {
        $productImages = new \app\modules\MubAdmin\modules\item\models\ProductImages();
        $success = $productImages::deleteAll(['title' => $name]);
        if($success)
        {
          return 'Image Deleted from Records'; 
        }
      }
      
  }else
  {
    return 'Go Awayyyy!';
  }
}

}

modules/MubAdmin/modules/item/views/product/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\helpers\ImageUploader;
use dosamigos\fileupload\FileUploadUI;
use app\modules\MubAdmin\modules\item\models\ProductImages;
$productImages = new ProductImages();
$mubUserId = \app\models\User::getMubUserId();
/* @var $this yii\web\View */
/* @var $product app\modules\MubAdmin\modules\item\products\Product */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="product-form">
    <div class="row">
    <div class="col-md-12">
        <h5><b>Product Images</b></h5>
        <?= FileUploadUI::widget([
        'model' => $productImages,
        'attribute' => 'thumbnail_url',
        'url' => ['product/product-image', 'userId' => $mubUserId],
        'gallery' => false,
        'fieldOptions' => [
            'accept' => 'image/*'
        ],
        'clientOptions' => [
            'maxFileSize' => 5000000,
            'load' => true
        ],
        'clientEvents' => [
            'fileuploaddone' => 'function(e, data) {
                                    console.log(e);
                                    console.log(data);
                                }',
            'fileuploadfail' => 'function(e, data) {
                                    console.log(e);
                                    console.log(data);
                                }',
        ],
        ]); ?></div>
    <?php $form = ActiveForm::begin(); ?>

    <div class="col-md-6"><?= $form->field($product, 'model_number')->textInput(['class' => 'border-input form-control']) ?></div>

    <div class="col-md-6"><?= $form->field($product, 'item_package_quantity')->dropDownList([ 'quantity' => 'Quantity', 'quantity2' => 'Quantity2', ], ['prompt' => '']) ?></div>

    <div class="col-md-6"><?= $form->field($product, 'size')->textInput(['class' => 'border-input form-control']) ?></div>

    <div class="col-md-6"><?= $form->field($product, 'size_map')->textInput(['class' => 'border-input form-control']) ?></div>

    <div class="col-md-6"><?= $form->field($product, 'color')->textInput(['class' => 'border-input form-control']) ?></div>

    <div class="col-md-6"><?= $form->field($product, 'color_map')->textInput(['class' => 'border-input form-control']) ?></div>

    <div class="col-md-6"><?= $form->field($product, 'enclosure_material')->textInput(['class' => 'border-input form-control']) ?></div>

    <div class="col-md-6"><?= $form->field($product, 'manufacturer')->textInput() ?></div>

    <div class="col-md-6"><?= $form->field($product, 'title')->textInput(['class' => 'border-input form-control']) ?></div>

    <div class="col-md-6"><?= $form->field($product, 'manufacturer_part_number')->textInput() ?></div>

    <div class="col-md-6"><?= $form->field($product, 'brand')->textInput() ?></div>

    <div class="col-md-6"><?php echo $form->field($product, 'category')->dropDownList($allcategory,['class' => 'border-input form-control'])->label('CATEGORY'); ?>
    </div>
    <div class="col-md-6"><?php echo $form->field($product, 'sub_category')->dropDownList([],['class' => 'border-input form-control'])->label('SUB CATEGORY'); ?>
    </div>

    <div class="col-md-6"><?= $form->field($product, 'seller_sku')->textInput(['class' => 'border-input form-control']) ?></div>

    <div class="col-md-6"><?= $form->field($product, 'HSN_code')->textInput(['class' => 'border-input form-control']) ?></div>

    <div class="col-md-6"><?= $form->field($product, 'price')->textInput() ?></div>

    <div class="col-md-6"><?= $form->field($product, 'sale_price')->textInput() ?></div>

    <div class="col-md-6"><?= $form->field($product, 'warranty_des')->textInput(['class' => 'border-input form-control']) ?></div>

    <div class="col-md-6"><?= $form->field($product, 'country')->textInput(['class' => 'border-input form-control']) ?></div>

    <div class="col-md-6"><?= $form->field($product, 'release_date')->textInput(['class' => 'border-input form-control']) ?></div>

    <div class="col-md-6"><?= $form->field($product, 'sale_start_date')->textInput(['class' => 'border-input form-control']) ?></div>

    <div class="col-md-6"><?= $form->field($product, 'sale_end_date')->textInput(['class' => 'border-input form-control']) ?></div>

    <div class="col-md-6"><?= $form->field($product, 'restock_date')->textInput(['class' => 'border-input form-control']) ?></div>

    <div class="col-md-6"><?= $form->field($product, 'offer_release_date')->textInput(['class' => 'border-input form-control']) ?></div>

    <div class="col-md-6"><?= $form->field($product, 'condition_notes')->textInput(['class' => 'border-input form-control']) ?></div>

    <div class="col-md-6"><?= $form->field($product, 'leagle_notes')->textInput(['class' => 'border-input form-control']) ?></div>

    <div class="col-md-6"><?= $form->field($product, 'quantity')->textInput() ?></div>

    <div class="col-md-6"><?= $form->field($product, 'max_order_quantity')->textInput() ?></div>

    <div class="col-md-6"><?= $form->field($product, 'product_text_code')->textInput(['class' => 'border-input form-control']) ?></div>

    <div class="col-md-6"><?= $form->field($product, 'condition')->textInput(['class' => 'border-input form-control']) ?></div>

    <div class="col-md-6"><?= $form->field($product, 'handling_time')->textInput(['class' => 'border-input form-control']) ?></div>

    <div class="col-md-6"><?= $form->field($product, 'gift_wrap')->dropDownList([ 'yes' => 'Yes', 'no' => 'No', ], ['prompt' => '']) ?></div>

    <div class="col-md-12"><?= $form->field($product, 'status')->dropDownList([ 'active' => 'Active', 'inactive' => 'Inactive', ], ['prompt' => 'Select Status']) ?></div>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?></div>
    </div>

</div>
</div>
    <?php ActiveForm::end(); ?>

</div>

modules/MubAdmin/modules/item/views/product/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $product app\modules\MubAdmin\modules\item\products\ProductSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="product-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($product, 'id') ?>

    <?= $form->field($product, 'mub_user_id') ?>

    <?= $form->field($product, 'model_number') ?>

    <?= $form->field($product, 'item_package_quantity') ?>

    <?= $form->field($product, 'size') ?>

    <?php // echo $form->field($product, 'size_map') ?>

    <?php // echo $form->field($product, 'color') ?>

    <?php // echo $form->field($product, 'color_map') ?>

    <?php // echo $form->field($product, 'enclosure_material') ?>

    <?php // echo $form->field($product, 'manufacturer') ?>

    <?php // echo $form->field($product, 'title') ?>

    <?php // echo $form->field($product, 'manufacturer_part_number') ?>

    <?php // echo $form->field($product, 'brand') ?>

    <?php // echo $form->field($product, 'category') ?>

    <?php // echo $form->field($product, 'sub_category') ?>

    <?php // echo $form->field($product, 'seller_sku') ?>

    <?php // echo $form->field($product, 'HSN_code') ?>

    <?php // echo $form->field($product, 'price') ?>

    <?php // echo $form->field($product, 'sale_price') ?>

    <?php // echo $form->field($product, 'warranty_des') ?>

    <?php // echo $form->field($product, 'country') ?>

    <?php // echo $form->field($product, 'release_date') ?>

    <?php // echo $form->field($product, 'sale_start_date') ?>

    <?php // echo $form->field($product, 'sale_end_date') ?>

    <?php // echo $form->field($product, 'restock_date') ?>

    <?php // echo $form->field($product, 'offer_release_date') ?>

    <?php // echo $form->field($product, 'condition_notes') ?>

    <?php // echo $form->field($product, 'leagle_notes') ?>

    <?php // echo $form->field($product, 'quantity') ?>

    <?php // echo $form->field($product, 'max_order_quantity') ?>

    <?php // echo $form->field($product, 'product_text_code') ?>

    <?php // echo $form->field($product, 'condition') ?>

    <?php // echo $form->field($product, 'handling_time') ?>

    <?php // echo $form->field($product, 'gift_wrap') ?>

    <?php // echo $form->field($product, 'status') ?>

    <?php // echo $form->field($product, 'created_at') ?>

    <?php // echo $form->field($product, 'updated_at') ?>

    <?php // echo $form->field($product, 'del_status') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/MubAdmin/modules/item/views/product/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $product app\modules\MubAdmin\modules\item\products\Product */

$this->title = 'Create Product';
$this->params['breadcrumbs'][] = ['label' => 'Products', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="product-create">

    <div class="row">
    	<div class="col-md-8 col-md-offset-2">
    		<div class="card">
    			<div class="header">

				    <p><?= Html::encode($this->title) ?></p>

				    <?= $this->render('_form', [
				        'product' => $product,
				        'allcategory' => $allcategory,
				        'allsubcategory' => $allsubcategory,
				    ]) ?>

				</div>
        </div>
    </div>
</div>

modules/MubAdmin/modules/item/views/product/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\modules\MubAdmin\modules\item\models\ProductSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Products';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="product-index">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="card">
                <div class="header">
                    <div class="row">
                        <div class="col-md-6">
                        <h1><?= Html::encode($this->title) ?></h1>
                        <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
                        </div>
                        <div class="col-md-6 text-right">
                        <p>
                            <?= Html::a('Create Product', ['create'], ['class' => 'btn btn-success']) ?>
                        </p>
                        </div>
                    </div>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            // 'mub_user_id',
            'model_number',
            // 'item_package_quantity',
            // 'size',
            //'size_map',
            //'color',
            //'color_map',
            //'enclosure_material',
            //'manufacturer',
            'title',
            //'manufacturer_part_number',
            //'brand',
            'category',
            'sub_category',
            //'seller_sku',
            //'HSN_code',
            'price',
            //'sale_price',
            //'warranty_des',
            //'country',
            //'release_date',
            //'sale_start_date',
            //'sale_end_date',
            //'restock_date',
            //'offer_release_date',
            //'condition_notes',
            //'leagle_notes',
            //'quantity',
            //'max_order_quantity',
            //'product_text_code',
            //'condition',
            //'handling_time',
            //'gift_wrap',
            'status',
            //'created_at',
            //'updated_at',
            //'del_status',

                    ['class' => 'yii\grid\ActionColumn'],
                ],
            ]); ?>
            <br/>
               </div>
            </div>
        </div>
    </div>
</div>

modules/MubAdmin/modules/item/views/product/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $product app\modules\MubAdmin\modules\item\products\Product */

$this->title = 'Update Product: {nameAttribute}';
$this->params['breadcrumbs'][] = ['label' => 'Products', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $product->title, 'url' => ['view', 'id' => $product->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="product-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'product' => $product,
        'allcategory' => $allcategory,
	    'allsubcategory' => $allsubcategory,
    ]) ?>

</div>

modules/MubAdmin/modules/item/views/product/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\modules\MubAdmin\modules\item\models\Product */

$this->title = $product->title;
$this->params['breadcrumbs'][] = ['label' => 'Products', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="product-view">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="card">
                <div class="header">
                <h1><?= Html::encode($this->title) ?></h1>

                <p>
                    <?= Html::a('Update', ['update', 'id' => $product->id], ['class' => 'btn btn-primary']) ?>
                    <?= Html::a('Delete', ['delete', 'id' => $product->id], [
                        'class' => 'btn btn-danger',
                        'data' => [
                            'confirm' => 'Are you sure you want to delete this item?',
                            'method' => 'post',
                        ],
                    ]) ?>
                </p>

                <?= DetailView::widget([
                    'model' => $product,
                    'attributes' => [
                        'id',
                        'mub_user_id',
                        'model_number',
                        'item_package_quantity',
                        'size',
                        'size_map',
                        'color',
                        'color_map',
                        'enclosure_material',
                        'manufacturer',
                        'title',
                        'manufacturer_part_number',
                        'brand',
                        'category',
                        'sub_category',
                        'seller_sku',
                        'HSN_code',
                        'price',
                        'sale_price',
                        'warranty_des',
                        'country',
                        'release_date',
                        'sale_start_date',
                        'sale_end_date',
                        'restock_date',
                        'offer_release_date',
                        'condition_notes',
                        'leagle_notes',
                        'quantity',
                        'max_order_quantity',
                        'product_text_code',
                        'condition',
                        'handling_time',
                        'gift_wrap',
                        'status',
                        'created_at',
                        'updated_at',
                        'del_status',
                    ],
                ]) ?>
             <br/>
            </div>
            </div>
        </div>
    </div>
</div>